[tool.black]
line-length = 100
target-version = ['py38']

[tool.isort]
profile = "black"
line_length = 100
known_third_party = []

[tool.flake8]
max-line-length = 100
extend-ignore = [
    "E203",  # Whitespace before ':'
    "W503",  # Line break before binary operator
]

[tool.bandit]
skips = ["B101"]

[tool.interrogate]
fail_under = 80  # Percentual mínimo de cobertura de docstrings
exclude = [
    "tests/*",
    "migrations/*",
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"

[tool.pydocstyle]
convention = "google"
